name: flutter_application_8
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Firebase core (required for all Firebase services)
  firebase_core: ^3.9.0
  
  # Firebase authentication
  firebase_auth: ^5.7.0
  
  # Firestore database
  cloud_firestore: ^5.6.12

  # Firebase Storage
  firebase_storage: ^12.3.2

  # (Optional) Google Sign-In support
  google_sign_in: ^6.2.2

  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
