// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzPXRhJ4CAw8bQmIo2yd3iU86oVx508c',
    appId: '1:946956936917:web:c29dd2bd9d64f92660645c',
    messagingSenderId: '946956936917',
    projectId: 'authtutorial-e10a8',
    authDomain: 'authtutorial-e10a8.firebaseapp.com',
    storageBucket: 'authtutorial-e10a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyex6MIQXbR5Nu376qQxFAmTEtFQCyteM',
    appId: '1:946956936917:android:02f27ed262c4d01b60645c',
    messagingSenderId: '946956936917',
    projectId: 'authtutorial-e10a8',
    storageBucket: 'authtutorial-e10a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErlPJ-s7tpNMdNbh3e3P0ptR_0SbHZh4',
    appId: '1:946956936917:ios:5da0e762532575e560645c',
    messagingSenderId: '946956936917',
    projectId: 'authtutorial-e10a8',
    storageBucket: 'authtutorial-e10a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErlPJ-s7tpNMdNbh3e3P0ptR_0SbHZh4',
    appId: '1:946956936917:ios:5da0e762532575e560645c',
    messagingSenderId: '946956936917',
    projectId: 'authtutorial-e10a8',
    storageBucket: 'authtutorial-e10a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzPXRhJ4CAw8bQmIo2yd3iU86oVx508c',
    appId: '1:946956936917:web:8eb933f63210cd0c60645c',
    messagingSenderId: '946956936917',
    projectId: 'authtutorial-e10a8',
    authDomain: 'authtutorial-e10a8.firebaseapp.com',
    storageBucket: 'authtutorial-e10a8.firebasestorage.app',
  );
}
